sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t stefania/docker-react -f Dockerfile.dev .

script:
  - docker-compose -f docker-compose-dev.yml up -d
#  - docker run -d -e CI=true stefania/docker-react npm run test 
  - docker ps
  - curl -v localhost:3000
deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'docker'
  env: 'docker-env'
  bucket_name: 'elasticbeanstalk-us-east-1-923445559289'
  bucket_path: 'docker'
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
