sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t stefania/docker-react -f Dockerfile.dev .

script:
#  - docker-compose -f docker-compose-dev.yml up -d
  - docker run -e CI=true stefania/docker-react npm run test 
  - docker ps
deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'docker-react'
  env: 'Dockerreact-env'
  bucket_name: 'elasticbeanstalk-us-east-1-878131601842'
  bucket_path: 'docker-react'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
